TMS.Web/Controllers/MaintenanceTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TMS.Domain.Entities;
using TMS.Infrastructure.Services;

namespace TMS.Web.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class MaintenanceTypeController : Controller
    {
        private readonly MaintenanceTypeService _maintenanceTypeService;
        private readonly VehicleMaintenanceService _vehicleMaintenanceService;

        public MaintenanceTypeController(MaintenanceTypeService maintenanceTypeService, VehicleMaintenanceService vehicleMaintenanceService)
        {
            _maintenanceTypeService = maintenanceTypeService;
            _vehicleMaintenanceService = vehicleMaintenanceService;
        }

        public async Task<IActionResult> Index()
        {
            var vehicles = await _maintenanceTypeService.GetAllMaintenanceTypesAsync();
            return View(vehicles);
        }

        [HttpGet("MaintenanceType/GetAllMaintenanceTypes")]
        public async Task<JsonResult> GetAllMaintenanceTypes()
        {
            var maintenanceType = await _maintenanceTypeService.GetAllMaintenanceTypesAsync();
            return Json(maintenanceType);
        }
        
        [HttpPost("MaintenanceType/AddVehicleMaintenance")]
        public async Task<JsonResult> AddVehicleMaintenance(VehicleMaintenance vehicleMaintenance)
        {
            var _vehicleMaintenance = await _vehicleMaintenanceService.AddVehicleMaintenanceAsync(vehicleMaintenance);
            return Json(new {Message= "Vehicle Maintenance Added Successfully", VehicleMaintenance = _vehicleMaintenance });
        }
        
        [HttpGet("MaintenanceType/GetMaintenanceTypeById/{maintenanceTypeId}")]
        public async Task<JsonResult> GetMaintenanceTypeById(int maintenanceTypeId)
        {
            var maintenanceType = await _maintenanceTypeService.GetMaintenanceTypeAsync(maintenanceTypeId);
            return Json(maintenanceType);
        }

        [HttpPost("MaintenanceType/Add")]
        public async Task<JsonResult> AddMaintenanceType(MaintenanceType maintenanceType)
        {
            var _maintenanceType = await _maintenanceTypeService.AddMaintenanceTypesAsync(maintenanceType);
            if (_maintenanceType is null)
                return Json(new { Message = "MaintenanceType Not Added", MaintenanceType = maintenanceType });
            return Json(new { Message = "MaintenanceType Added Successfully", MaintenanceType = _maintenanceType });
        }
        
        [HttpPost("MaintenanceType/Update")]
        public async Task<JsonResult> UpdateMaintenanceType(MaintenanceType maintenanceType)
        {
            var _maintenanceType = await _maintenanceTypeService.UpdateMaintenanceTypesAsync(maintenanceType);
            if (_maintenanceType is null)
                return Json(new { Message = "MaintenanceType Not Updated", MaintenanceType = maintenanceType });
            return Json(new { Message = "MaintenanceType Updated Successfully", MaintenanceType = _maintenanceType });
        }
        
        [HttpPost("MaintenanceType/Delete")]
        public async Task<JsonResult> DeleteMaintenanceType(MaintenanceType maintenanceType)
        {
            var _maintenanceType = await _maintenanceTypeService.RemoveMaintenanceTypesAsync(maintenanceType);
            if (_maintenanceType is null)
                return Json(new { Message = "MaintenanceType Not Added", MaintenanceType = maintenanceType });
            return Json(new { Message = "MaintenanceType Deleted Successfully", VeMaintenanceTypehicle = _maintenanceType });
        }
    }
}

TMS.Web/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TMS.Domain.Entities;
using TMS.Infrastructure.Services;

namespace TMS.Web.Controllers;

[Authorize(Roles = "Admin,User")]
public class VehicleController : Controller
{
    private readonly VehicleService _vehicleService;

    public VehicleController(VehicleService vehicleService)
    {
        _vehicleService = vehicleService;
    }

    public async Task<IActionResult> Index()
    {
        var vehicles = await _vehicleService.GetAllVehiclesAsync();
        return View(vehicles);
    }

    [HttpGet("Vehicle/GetVehicleById/{vehicleId}")]
    public async Task<JsonResult> GetVehicleById(int vehicleId)
    {
        var vehicle = await _vehicleService.GetVehicleAsync(vehicleId);
        return Json(vehicle);
    }

    [HttpPost("Vehicle/Add")]
    public async Task<JsonResult> AddVehicle(Vehicle vehicle)
    {
        var _vehicle = await _vehicleService.AddVehicleAsync(vehicle);
        if (_vehicle is null)
            return Json(new { Message = "Vehicle Not Added", Vehicle = vehicle });
        return Json(new { Message = "Vehicle Added Successfully", Vehicle = _vehicle });
    }
    
    [HttpPost("Vehicle/Update")]
    public async Task<JsonResult> UpdateVehicle(Vehicle vehicle)
    {
        var _vehicle = await _vehicleService.UpdateVehicleAsync(vehicle);
        if (_vehicle is null)
            return Json(new { Message = "Vehicle Not Updated", Vehicle = vehicle });
        return Json(new { Message = "Vehicle Updated Successfully", Vehicle = _vehicle });
    }
    
    [HttpPost("Vehicle/Delete")]
    public async Task<JsonResult> DeleteVehicle(Vehicle vehicle)
    {
        var _vehicle = await _vehicleService.RemoveVehicleAsync(vehicle);
        if (_vehicle is null)
            return Json(new { Message = "Vehicle Not Added", Vehicle = vehicle });
        return Json(new { Message = "Vehicle Deleted Successfully", Vehicle = _vehicle });
    }
}

TMS.Web/Controllers/VehicleMaintenanceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TMS.Domain.Entities;
using TMS.Infrastructure.Services;

namespace TMS.Web.Controllers;

[Authorize(Roles = "Admin,User")]
public class VehicleMaintenanceController : Controller
{
    private readonly MaintenanceTypeService _maintenanceTypeService;
    private readonly VehicleMaintenanceService _vehicleMaintenanceService;

    public VehicleMaintenanceController(MaintenanceTypeService maintenanceTypeService, VehicleMaintenanceService vehicleMaintenanceService)
    {
        _maintenanceTypeService = maintenanceTypeService;
        _vehicleMaintenanceService = vehicleMaintenanceService;
    }

    public async Task<IActionResult> Index()
    {
        var vehicleMaintenances = await _vehicleMaintenanceService.GetAllVehiclesWithMaintenancesAsync();
        return View(vehicleMaintenances);
    }

    [HttpPost("VehicleMaintenance/Delete")]
    public async Task<JsonResult> DeleteVehicle(VehicleMaintenance vehicleMaintenance)
    {
        var _vehicleMaintenance = await _vehicleMaintenanceService.RemoveVehicleMaintenanceAsync(vehicleMaintenance.Id);
        if (_vehicleMaintenance is null)
            return Json(new { Message = "VehicleMaintenance Not Deleted", VehicleMaintenance = _vehicleMaintenance });
        return Json(new { Message = "VehicleMaintenance Deleted Successfully", VehicleMaintenance = _vehicleMaintenance });
    }
}

TMS.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<TMS.Domain.Entities.ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TMS.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TMS.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TMS.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole(TMS.Domain.Enums.ERoles.Admin.ToString()))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MaintenanceType" asp-action="Index">MaintenanceType</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="Index">Vehicle</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="VehicleMaintenance" asp-action="Index">VehicleMaintenance</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TMS.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>